name: Build and Release


on:
  release:
    types: [published]

env:
  BUILD_TYPE: Release


jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            deps_command: |
              sudo apt update
              sudo apt install -y libglew-dev libgtk-3-dev
              git clone https://github.com/glfw/glfw
              cmake -S glfw -B glfw/build -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
              git clone https://github.com/nigels-com/glew
              make -C glew/auto && make -C glew && sudo make -C glew install
              cmake --build glfw/build && sudo make -C glfw/build install
            config_command: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$BUILD_TYPE -DGLEW_USE_STATIC_LIBS=1
            build_command: |
              cmake --build build --config $BUILD_TYPE
              mv build/$BUILD_TYPE/SotN_Editor ./SotN_Editor
              7z a SotN_Editor_Linux.zip SotN_Editor
            artifact: SotN_Editor_Linux.zip
          - os: macos-latest
            deps_command: |
              brew install gtk+3 glew
              git clone https://github.com/glfw/glfw
              cmake -S glfw -B glfw/build -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
              cmake --build glfw/build && sudo make -C glfw/build install
            config_command: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$BUILD_TYPE -DGLEW_USE_STATIC_LIBS=1
            build_command: |
              cmake --build build --config $BUILD_TYPE
              tar -cvf build/$BUILD_TYPE/SotN_Editor.tar -C build/$BUILD_TYPE SotN_Editor.app
              mv build/$BUILD_TYPE/SotN_Editor.tar ./SotN_Editor.tar
              7z a SotN_Editor_macOS.zip SotN_Editor.tar
            artifact: SotN_Editor_macOS.zip
          - os: windows-latest
            deps_command: git clone https://github.com/microsoft/vcpkg.git
            config_command: cmake -B build -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static
            build_command: |
              cmake --build build --config $env:BUILD_TYPE
              move build/$env:BUILD_TYPE/SotN_Editor.exe SotN_Editor.exe
              7z a SotN_Editor_Windows.zip SotN_Editor.exe
            artifact: SotN_Editor_Windows.zip

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Dependencies
        run: ${{matrix.deps_command}}

      - name: Configure
        run: ${{matrix.config_command}}

      - name: Build
        run: ${{matrix.build_command}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SotN-Editor-${{matrix.os}}-build
          path: ${{matrix.artifact}}
          retention-days: 7

  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: SotN Editor ${{ github.ref_name }}
          files: |
            SotN-Editor-ubuntu-latest-build/*
            SotN-Editor-windows-latest-build/*
            SotN-Editor-macos-latest-build/*
          generate_release_notes: true
